# fly.toml app configuration file generated for qr-code-poc2 on 2024-03-13T14:37:58+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qr-code-poc2'
primary_region = 'sin'

[env]

PORT = "8081"
SHOPIFY_APP_URL = "https://qr-code-poc2.fly.dev"
SHOPIFY_API_KEY = "9ad2da8a749426016d0cfe7621eccfd4"
SCOPES = "write_products"


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
